app/views/mypage.py
from flask import Blueprint , render_template ,request,make_response,redirect,url_for,session
from PIL import Image
from werkzeug.utils import secure_filename
from datetime import datetime , timedelta
import mysql.connector
import json
import os

#DB設定------------------------------------------------------------------------------------------------------------------------------------------------------------------
def connect_db():
    con=mysql.connector.connect(
        host = 'localhost',
        user = 'root',
        passwd = '',
        db ='db_subkari'
    )
    return con
#------------------------------------------------------------------------------------------------------------------------------------------------------

#価格をカンマ区切りにして返す ----------------------------------------------------
def comma(num):
    #0が来た場合の処理
    if num==0:
        return str(num)
    
    string1=""
    string2=""
    if type(num)=="string":
        num=int(num)
    tmp=num
   
    count=0
 
    while tmp/10!=0:
        string1+=str(tmp%10)
        tmp//=10
        count+=1
        if count%3==0 :
            string1+=","
            count+=1
    tmp=0
    while tmp<count:
        string2+=string1[count-tmp-1]
        tmp+=1

    return string2
    

#アカウントの口座情報を取得する ------------------------------------------------------------------------------
def getAccountInfo():
    accountNumbers=[]                 #口座番号下位三桁を格納
    id=session["user_id"]
    editmode=session["editmode"]
    con=connect_db()
    cur=con.cursor(dictionary=True)
    sql="select bankName,accountNumber,branchCode from t_transfer  where account_id=%s limit 3"
    cur.execute(sql,(id,))
    bank_info=cur.fetchall()
    cur.close()
    con.close()
    count=0
    #口座がいくつ登録されているかを数える
    for i in bank_info:
        count+=1

    #口座番号マスク処理のために口座番号の桁数と下位三桁を抽出し配列に入れる
    for i in range(count):
        num=int(bank_info[i]['accountNumber'])

        tmp=num
        length=0
        mask=""
        #口座番号の桁数を取得
        while tmp>0:
            tmp=tmp//10
            length+=1
        for i in range(length-3):
        
            mask+="*"

        num=str(num%1000)
        num=mask+num                #マスク処理を施した口座番号
        accountNumbers.append(num)
    return bank_info,accountNumbers,count

#ユーザー情報を取得する ------------------------------------------------------------------------------------
#引数として受け取ったidを持つユーザーの情報を取得
def get_user_info(id):
    sql = "SELECT * FROM m_account WHERE id = %s"
    con = connect_db()
    cur = con.cursor(dictionary=True)
    cur.execute(sql, (id,))  # ← タプルで渡す！
    user_info = cur.fetchone()
    return user_info


#プロフィールに表示する取引情報を取得する ------------------------------------------------------------------------------------
#引数として受け取ったidを持つユーザーの情報を取得
def get_transaction_info(id):
    #アカウントテーブルからは取れない情報を取得
    con = connect_db()
    cur = con.cursor(dictionary=True)
    #フォロワー数、フォロー数、評価、総評価件数、出品数を取得
    #フォロー数
    sql="select count(*) as フォロー数 from t_connection where execution_id=%s and type='フォロー' group by execution_id"
    cur.execute(sql, (id,))
    follows=cur.fetchone()
    #フォロワー数
    sql="select count(*) as フォロワー数 from t_connection where target_id=%s and type='フォロー' group by target_id"
    cur.execute(sql, (id,))
    followers=cur.fetchone()
    #評価
    sql="select avg(score) as 評価 from t_evaluation where recipient_id=%s group by recipient_id"
    cur.execute(sql, (id,))
    evaluation=cur.fetchone()
    #総評価件数
    sql="select count(*) as 評価件数 from t_evaluation where recipient_id=%s group by recipient_id"
    cur.execute(sql, (id,))
    evaluationCount=cur.fetchone()
    #出品数
    sql="select count(*) as 出品数 from m_product where account_id=%s"
    cur.execute(sql, (id,))
    products=cur.fetchone()
    #評価を変形

    if followers is None:
        followers={'フォロワー数':0}
    if follows is None:
        follows={'フォロー数':0}
    if products is None:
        products={'出品数':0}
    


    if evaluation is not None:


        evaluation['評価'] = round(float(evaluation['評価']))
    #小数点型にしてから四捨五入
    else:
        evaluation = {"評価":0}



    return evaluation,evaluationCount,follows,followers,products

#商品データを取得 --------------------------------------------------
def get_product_info(id):

    con = connect_db()
    cur = con.cursor(dictionary=True)
    #商品idを取得
    sql="select id from m_product where account_id=%s"
    cur.execute(sql,(id,))
    product_id=cur.fetchall()
    #商品名を取得
    sql="select name from m_product where account_id=%s"
    cur.execute(sql,(id,))
    name=cur.fetchall()
    #各商品1枚目の画像を取得 
    sql="SELECT  i.* FROM m_productImg i INNER JOIN (SELECT  product_id,MIN(id) AS first_image_id FROM m_productImg GROUP BY product_id) AS first_img ON i.id = first_img.first_image_id INNER JOIN m_product p ON p.id = i.product_id WHERE p.account_id = %s"
    cur.execute(sql,(id,))
    img=cur.fetchall()
    cur.close()
    con.close()

    return product_id,name,img

#mypageこういう名前のモジュール
mypage_bp = Blueprint('mypage', __name__, url_prefix='/mypage')


# ---------------------------------------------------------------------------------------------



#マイページトップ表示-----------------------------------------------------------------------------
@mypage_bp.route("/mypage")
def mypage():
    if 'user_id' not in session:
        user_id = None
        return redirect(url_for('login.login'))
    else:
        user_id = session.get('user_id')

    
    
    #アカウントテーブルからユーザー情報を取得
    user_info=get_user_info(user_id)
    evaluation,evaluationCount,follows,followers,products=get_transaction_info(user_id)

    con=connect_db()
    cur=con.cursor(dictionary=True)
    
    #売上履歴を取得
    #売上履歴から売上金を計算する
    sql="select p.id ,ti.created_at, case when t.situation='購入' then p.purchasePrice else p.rentalPrice end as price from t_transaction t inner join m_product  p on t.product_id=p.id left join t_time ti on t.id=ti.transaction_id where t.status='取引完了' and p.account_id=%s group by ti.created_at,t.seller_id"
    cur.execute(sql,(user_id,))
    sales=cur.fetchall()
    total=0
    for sale in sales:
        total+=int(sale['price'] if sale['price'] else 0)
    total=comma(total)

    return render_template("mypage/mypage.html",
    evaluation=evaluation,evaluationCount=evaluationCount,follows=follows,
    followers=followers,products=products,user_info=user_info ,user_id=user_id,total=total)
    
#------------------------------------------------------------------------------------------------


#editProfile プロフィール編集ページ表示--------------------------------------------------------------
@mypage_bp.route("/editProfile")
def editProfile():
    if 'user_id' not in session:
        user_id = None
        return redirect(url_for('login.login'))
    else:
        user_id = session.get('user_id')
    
    #user情報を取得
    user_info=get_user_info(user_id)
    evaluation,evaluationCount,follows,followers,products=get_transaction_info(user_id)
    #商品情報を取得
    productId,productName,productImg=get_product_info(user_id)
    print(productId)
    return render_template("mypage/editProfile.html",evaluation=evaluation,evaluationCount=evaluationCount,follows=follows,followers=followers,products=products,productId=productId,productName=productName,productImg=productImg,user_info=user_info,user_id=user_id)

#updateProfile プロフィール更新--------------------------------------------------------------
@mypage_bp.route("/updateProfile",methods=['POST'])
def updateProfile():
    if 'user_id' not in session:
        user_id = None
        return redirect(url_for('login.login'))
    else:
        user_id = session.get('user_id')
    #更新内容を取得
    new_profile=request.form   #username,smoker,introduction

    id=session['user_id']

    #dbに更新をかける 
    con = connect_db()
    cur = con.cursor(dictionary=True)
    sql="update m_account set username=%s,smoker=%s,introduction=%s where id=%s"
    cur.execute(sql,(new_profile['username'],new_profile['smoker'],new_profile['introduction'],id))
    con.commit()
    cur.close()
    con.close()

    #更新後のユーザー情報を取得 
    user_info=get_user_info(id)
    evaluation,evaluationCount,follows,followers,products=get_transaction_info(id)
    productId,productName,productImg=get_product_info(id)
    return render_template("mypage/editProfile.html",user_info=user_info,productId=productId,evaluation=evaluation,evaluationCount=evaluationCount,follows=follows,followers=followers,products=products,productName=productName,productImg=productImg,user_id=user_id)

    
#--------------------------------------------------------------------------------------------------

#edit プロフィール編集-------------------------------------------------------------------------------
@mypage_bp.route("/edit")
def edit():
    if 'user_id' not in session:
        user_id = None
        return redirect(url_for('login.login'))
    else:
        user_id = session.get('user_id')

    #ユーザー情報を取得
    user_info=get_user_info(user_id)

    return render_template("mypage/edit.html", user_info=user_info,user_id=user_id)
    

#--------------------------------------------------------------------------------------------------


#bankRegistration　振込口座登録ページ表示--------------------------------------------------------------
@mypage_bp.route("/bankRegistration")
def bankRegistration():

    #登録されている口座数を取得
    bank_count=0
    id=session["user_id"]
    con=connect_db()
    cur=con.cursor(dictionary=True)

    sql="select count(*) as 登録数 from t_transfer t inner join m_account a on t.account_id=a.id where a.id=%s group by a.id"
    cur.execute(sql,(id,))
    
    bank_count=cur.fetchone()
    if bank_count==None:
        bank_count=0
    else:
        bank_count=int(bank_count["登録数"])
    
    
    cur.close()
    con.close()
    #3件すでに登録済みなら拒否する
    if bank_count>=3:
    #     return render_template("mypage/mypage.html",user_id=user_id)
    
    # return render_template("mypage/bankRegistration.html",user_id=user_id)
        return render_template("mypage/mypage.html")
    
    return render_template("mypage/bankRegistration.html")

app/views/userprf.py
from flask import Blueprint , render_template ,request,make_response,redirect,url_for,session
from PIL import Image
from werkzeug.utils import secure_filename
from datetime import datetime , timedelta
import mysql.connector
import json
import os

#DB設定------------------------------------------------------------------------------------------------------------------------------------------------------------------
def connect_db():
    con=mysql.connector.connect(
        host = 'localhost',
        user = 'root',
        passwd = '',
        db ='db_subkari'
    )
    return con
#------------------------------------------------------------------------------------------------------------------------------------------------------
#ユーザー情報を取得する ------------------------------------------------------------------------------------
#引数として受け取ったidを持つユーザーの情報を取得
def get_user_info(id):
    sql = "SELECT * FROM m_account WHERE id = %s"
    con = connect_db()
    cur = con.cursor(dictionary=True)
    cur.execute(sql, (id,))  # ← タプルで渡す！
    user_info = cur.fetchone()
    return user_info


#プロフィールに表示する取引情報を取得する ------------------------------------------------------------------------------------
#引数として受け取ったidを持つユーザーの情報を取得
def get_transaction_info(id):
    #アカウントテーブルからは取れない情報を取得
    con = connect_db()
    cur = con.cursor(dictionary=True)
    #フォロワー数、フォロー数、評価、総評価件数、出品数を取得
    #フォロー数
    sql="select count(*) as フォロー数 from t_connection where execution_id=%s and type='フォロー' group by execution_id"
    cur.execute(sql, (id,))
    follows=cur.fetchone()
    #フォロワー数
    sql="select count(*) as フォロワー数 from t_connection where target_id=%s and type='フォロー' group by target_id"
    cur.execute(sql, (id,))
    followers=cur.fetchone()
    #評価
    sql="select avg(score) as 評価 from t_evaluation where recipient_id=%s group by recipient_id"
    cur.execute(sql, (id,))
    evaluation=cur.fetchone()
    #総評価件数
    sql="select count(*) as 評価件数 from t_evaluation where recipient_id=%s group by recipient_id"
    cur.execute(sql, (id,))
    evaluationCount=cur.fetchone()
    #出品数
    sql="select count(*) as 出品数 from m_product where account_id=%s"
    cur.execute(sql, (id,))
    products=cur.fetchone()
    #評価を変形

    if followers is None:
        followers={'フォロワー数':0}
    if follows is None:
        follows={'フォロー数':0}
    if products is None:
        products={'出品数':0}
    


    if evaluation is not None:


        evaluation['評価'] = round(float(evaluation['評価']))
    #小数点型にしてから四捨五入
    else:
        evaluation = {"評価":0}
        



    return evaluation,evaluationCount,follows,followers,products

#商品データを取得 --------------------------------------------------
def get_product_info(id):

    con = connect_db()
    cur = con.cursor(dictionary=True)

    #商品idを取得
    sql="select id from m_product where account_id=%s"
    cur.execute(sql,(id,))
    product_id=cur.fetchall()
    #商品名を取得
    sql="select name from m_product where account_id=%s"
    cur.execute(sql,(id,))
    name=cur.fetchall()
    #各商品1枚目の画像を取得 
    sql="SELECT  i.* FROM m_productImg i INNER JOIN (SELECT  product_id,MIN(id) AS first_image_id FROM m_productImg GROUP BY product_id) AS first_img ON i.id = first_img.first_image_id INNER JOIN m_product p ON p.id = i.product_id WHERE p.account_id = %s"
    cur.execute(sql,(id,))
    img=cur.fetchall()
    cur.close()
    con.close()

    return product_id,name,img


# Blueprintの設定
userprf_bp = Blueprint('userprf', __name__, url_prefix='/userprf')


#userprf ユーザープロフィールを表示------------------------------------------------------
# @userprf_bp.route("/<int:userprf_id>" )
@userprf_bp.route("/userprf" ,methods=["POST","GET"])
def userprf():
    if 'user_id' not in session:
        user_id = None
        return redirect(url_for('login.login'))
    else:
        user_id = session.get('user_id')
    id=request.form.get("id")
    
    #user情報を取得
    user_info=get_user_info(id)
    evaluation,evaluationCount,follows,followers,products=get_transaction_info(id)
    #商品情報を取得
    productId,productName,productImg=get_product_info(id)
 
  
    return render_template("userprf/userprf.html",evaluation=evaluation,evaluationCount=evaluationCount,follows=follows,followers=followers,products=products,productId=productId,productName=productName,productImg=productImg,user_info=user_info,user_id=user_id)


#--------------------------------------------------------------------------------------

app/templates/mypage/amountComp.html
{% extends "base.html" %}
{% block title %}
金額確定
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/amountComp.css') }}">
<main>
    <div class="container">
        <div class="header">
            <h1>振込金額が確定しました</h1>
        </div>
        <div class="header">
                <p class="subtitle">以下の内容で振込処理が完了いたしました</p>

        </div>


        <div class="amount-section">
            <div class="amount-label">振込金額</div>
            <div class="amount">¥150,000</div>
            <div class="amount-detail">（消費税込み）</div>
        </div>
        <div class="info-section">
            <div class="info-row">
                <span class="info-label">振込先口座</span>
                <span class="info-value">みずほ銀行 渋谷支店</span>
            </div>
            <div class="info-row">
                <span class="info-label">口座番号</span>
                <span class="info-value">普通 1234567</span>
            </div>
            <div class="info-row">
                <span class="info-label">口座名義</span>
                <span class="info-value">ヤマダ タロウ</span>
            </div>
            <div class="info-row">
                <span class="info-label">取引番号</span>
                <span class="info-value">TRX-20251028-00123</span>
            </div>
        </div>
        <div class="message">
            <p class="message-text">
                ✓ 振込処理が正常に完了しました。<br>
                ✓ 確認メールを登録のメールアドレスに送信いたしました。<br>
                ✓ 通常1〜2営業日以内に口座へ反映されます。
            </p>
        </div>
        <div class="button-group">
            <form action="{{ url_for('mypage.mypage') }}">
                <button class="btn btn-primary">マイページへ戻る</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

app/templates/mypage/edit.html
{% extends "base.html" %}
{% block title %}
    プロフィール編集
{% endblock %}

{% block content %}
<link rel="stylesheet" href="../../static/css/edit.css">
<main>
    <div class="container">
        <h1>プロフィール編集</h1>

        <form action="{{url_for('mypage.updateProfile')}}" method="post" id="account_info">
            <!-- 画像 -->
            <div class="form-section">
                <div class="section-title">画像</div>
                <div class="image-upload">
                    <img src="{{url_for('static' , filename='img/'+user_info.identifyfrontImg)}}" alt="プロフィール画像" class="profile-image">

                    <input type="file" id="imageInput" style="display: none;" accept="image/*" onchange="previewImage(event)">
                    <button type="button" class="upload-btn" onclick="document.getElementById('imageInput').click()">画像を選択</button>
                </div>
            </div>

            <!-- 喫煙の有無 -->
            <div class="form-section">
                <p class="section-title">喫煙の有無</p>
                <div class="radio-group">
                    <div class="radio-item">
                        <input type="radio" id="smoking1" name="smoker" value="0" 
                            {% if user_info.smoker == 0 %}checked{% endif %}>
                        <label for="smoking1">喫煙者</label>
                    </div>
                    <div class="radio-item">
                        <input type="radio" id="smoking2" name="smoker" value="1" 
                            {% if user_info.smoker == 1 %}checked{% endif %}>
                        <label for="smoking2">非喫煙者</label>
                    </div>
                </div>
            </div>
            <!-- アカウント名 -->
            <div class="form-group">
                <label class="form-label">アカウント名</label>
                <input type="text" class="form-input" id="accountName" name="username"value="{{user_info.username}}" maxlength="20" oninput="updateCharCount('accountName', 'nameCount', 20); validateAccountName()">
                <div class="error-message" id="nameError" >アカウント名を入力してください</div>
                <div class="char-count"><span id="nameCount">0</span> / 20</div>
            </div>

            <!-- 自己紹介 -->
            <div class="form-group">
                <label class="form-label">自己紹介</label>
                <textarea class="form-textarea" id="bio" maxlength="1000" oninput="updateCharCount('bio', 'bioCount', 1000); validateBio()" name="introduction">{% if user_info.introduction!='None' %}{{user_info.introduction}}{% else %}{% endif %}</textarea>
                <div class="error-message" id="bioError">1000文字以下で入力してください</div>
                <div class="char-count" id="bioCountWrapper"><span id="bioCount">0</span> / 1000</div>
            </div>

            <!-- 送信ボタン -->
            <div class="submit-section">
                <button type="submit" class="submit-btn" onclick="handleSubmit(event)">更新する</button>
            </div>
        </form>
    </div>
    <script src="../../static/js/edit.js"></script>
</main>
{% endblock %} 

app/templates/mypage/editProfile.html
{% extends "base.html" %}
{% block title %}
    編集ボタンありプロフィール
{% endblock %}

{% block content %}
<!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/editProfile.css') }}"> -->

<link rel="stylesheet" href="../../static/css/editProfile.css">
    <main class="editProfile_main">
        <h1>ユーザープロフィール</h1>
        <div class="profile-header">
            <img src="{{url_for('static' , filename='img/'+user_info.profileImage)}}" alt="プロフィール画像" class="profile-image">
            <div class="profile-info">
                <h1 class="profile-name">{{user_info.username}}</h1>
                
                <div class="profile-rating">
                    <span class="stars">
                    {% for i in range(evaluation.評価)%}★{% endfor %}{% for i in range(5-evaluation.評価)%}☆{% endfor %}</span>
                    <span class="rating-count">{{evaluationCount.評価件数}}</span>
                    {% if user_info.smoker == 0%}
                        <span class="reviewer-badge">喫煙者</span>
                    {% else %}
                        <span class="reviewer-badge">非喫煙者</span>
                    {% endif %} 
                </div>
                
                <div class="profile-stats">
                    <div class="stat-item">
                        <span class="stat-number">{{products.出品数}}</span>
                        <span class="stat-label">出品数</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-number">{{follows.フォロー数}}</span>
                        <span class="stat-label">フォロー</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-number">{{followers.フォロワー数}}</span>
                        <span class="stat-label">フォロワー</span>
                    </div>
                </div>
                
                <div class="profile-description" id="profileDescription">
                    {% if user_info.introduction!='None' %}
                    {{user_info.introduction}}
                    {% else %}

                    {% endif %}
                    <span id="moreText" style="display: none;">
                        <br><br>
                        【取引について】<br>
                        ・購入時すぐに気持ちメッセージをお願いいたします。<br>
                        ・発送時期は平日夕方となっています。基本即日発送はできません。プロフィルをしっかりと読んでいただくと判断した場合ものよっては取引を解除させていただきますので、安心して取引できない相手と判断し、評価は「悪い」にさせていただきます。
                    </span>
                </div>
                
                <a href="#" class="show-more" id="showMoreBtn" onclick="toggleDescription(event)">もっと見る</a>
                <a href="#" class="show-more" id="showLessBtn" onclick="toggleDescription(event)" style="display: none;">閉じる</a>
            </div>
            
           <div class="profile-actions" ><a href="{{url_for('mypage.edit')}}">
                <button class="edit-profile-btn">プロフィールを編集</button>
            </div>
            </a>
        </div>

        <!-- 商品グリッド -->
            <div class="products-grid">
                {% if productName %}
                {% for name in productName %}
                <form action="{{ url_for('products.product_details_stub', product_id=productId[loop.index0]["id"]) }}" method="get"> <!--商品詳細へ遷移-->

      
                    <button>
                        {% if productImg %}
                        <img src="{{url_for('static',filename='img/productImg/'+productImg[loop.index0]["img"])}}" alt="{{name.name}}の画像" class="product-image">
                    </button>
                        {% else %}
                        <p>画像がありません</p>
                        {% endif %}
                    <div class="product-name" name="product_name">{{productName[loop.index0]["name"]}}</div>
                    
                </form>

                {% endfor %}
                {% else %}
                <p>まだ出品していません</p>
                {% endif %}
            </div>
       
        <!-- もっと見るボタン -->
        <div class="load-more">
            <button class="load-more-btn">もっと見る</button>
        </div>
    </main>


    <script src="../../static/js/editProfile.js"></script>
{% endblock %} 

app/templates/mypage/followList.html
{% extends "base.html" %}
{% block title %}
    フォローリスト表示
{% endblock %}

{% block content %}
<link rel="stylesheet" href="../../static/css/followList.css">
<!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/followList.css') }}"> -->

<main>
    <h1>フォローリスト</h1>
    <div class="sales-list">
        {% if follow_list %}
            {% for user in follow_list %}
            <form action="{{ url_for('userprf.userprf') }}" method="post">
                <input type="hidden" name="id" value="{{ user.id }}">
                <button type="submit" class="sales-item">
                    <div class="user-info">
                        <img src="{{ url_for('static', filename='img/'+user.アイコン) }}" class="profile-image">
                        <div class="profile-name">{{user.ユーザー名}}</div>
                    </div>
                    <div class="profile-rating">
                        <span class="stars">
                            {% for i in range(user.評価) %}★{% endfor %}
                            {% for i in range(5-user.評価) %}☆{% endfor %}
                        </span>
                        <div class="rating-count">{{user.評価件数}}</div>
                    </div>
                </button>
            </form>

            {% endfor %}
        {% else %}
            <p>まだフォローしていません</p>
        {% endif %}
    </div>
</main>
{% endblock %}

app/templates/mypage/likes.html
{% extends "base.html" %}
{% block title %}
    いいねページ
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/likes.css') }}">
<main>
    <h1>いいね一覧</h1>
    <div class="sales-list">
        {% if likes_list %}
            {% for item in likes_list %}
                <a href="{{ url_for('products.product_details_stub', product_id=item.id) }}" class="sales-item-link">
                    <div class="sales-item">
                        <p>
                            <img src="{{ url_for('static', filename='img/' + (item.image_path or 'default.png')) }}" alt="商品画像" class="item-image">
                        </p>
                        <div class="sales-info">
                            <div class="sales-name">{{ item.name }}</div>
                            <div class="sales-amount">
                                {% if item.purchaseFlg|int == 1 and item.rentalFlg|int == 1 %}
                                    {% if item.purchasePrice %}購入: ¥{{ "{:,}".format(item.purchasePrice) }}<br>{% endif %}
                                    {% if item.rentalPrice %}レンタル: ¥{{ "{:,}".format(item.rentalPrice) }}{% endif %}
                                {% elif item.purchaseFlg|int == 1 and item.purchasePrice %}
                                    購入: ¥{{ "{:,}".format(item.purchasePrice) }}
                                {% elif item.rentalFlg|int == 1 and item.rentalPrice %}
                                    レンタル: ¥{{ "{:,}".format(item.rentalPrice) }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <p>いいねされた商品はまだありません。</p>
        {% endif %}
    </div>
</main>

{% endblock %}

app/templates/mypage/transaction_detail.html
<!-- このページ無理,,,表示しない -->
{% extends "base.html" %}

{% block title %}取引詳細{% endblock %}

{% block content %}



    <!-- <link rel="stylesheet" href="../../../app/static/css/transaction_detail.css">  -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/transaction_detail.css') }}">


<main class="container">
    <div class="transaction-container">
        <section class="transaction-info">
            <h2>取引情報</h2>
            <div class="product-detail">
                <img class="product-image" src="{{img}}" alt="aa">
                <div class="product-name">{{name}}</div>
            </div>

            <div class="info-list">
                <div class="info-row">
                   <input type="hidden" name="customer_id" value="{{customer_id}}">
                </div>
                <div class="info-row">
                    <div class="info-label">商品代金</div>
                    <div class="info-value">{{price}}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">販売手数料</div>
                    <div class="info-value">{{fee}}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">販売利益</div>
                    <div class="info-value">{{profit}}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">購入日時</div>
                    <div class="info-value">{{datetime}}</div>
                </div>
                <div class="info-row">
                    <div class="info-label">配送の方法</div>
                    <div class="info-value">普通郵便</div>
                </div>
                <div class="info-row">
                    <div class="info-label">商品ID</div>
                    <div class="info-value">{{id}}</div>
                </div>
            </div>
        </section>

        <section class="buyer-info">
            <h2>購入者情報</h2>           

            <form action="{{url_for('mypage.edit')}}">
                <a href="../userprf/userprf.html" class="buyer-profile">
                    <div class="buyer-left">
                        <div class="buyer-avatar">
                        </div>
                        <div class="buyer-name-rating">
                            <div class="buyer-name">haltaro</div>
                            <div class="rating-badges">
                                <span class="rating-star">⭐⭐⭐⭐⭐</span>
                                <span class="rating-count">255</span>
                                <span class="badge-verified">本人確認済</span>
                                <span class="badge-other">喫煙者</span>
                            </div>
                        </div>
                    </div></a>
                    <div class="list-item-arrow">
                        &gt; </div>
                </a>
            </form>
        </section>
    </div>
</main>


{% endblock %}